name: API Handler

on:
  repository_dispatch:
    types: [api-request]
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to process'
        required: true

jobs:
  handle-request:
    runs-on: ubuntu-latest

    steps:
      - name: Handle API Request
        id: api
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        run: |
          message="${{ github.event.inputs.message }}"
          response=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_KEY" \
            -d '{
              "model": "gpt-3.5-turbo",
              "messages": [{"role": "user", "content": "'"$message"'"}]
            }')
          echo "Response: $response"
